test:
  adapter: postgresql
  pool: 5
  database: mobimonitor_test

development:
  adapter: postgresql
  pool: 5
  database: mobimonitor_development

production:
  adapter: postgresql
  pool: 5
  database: mobimonitor_production
